2017-12-28 12:01:33.768 [error] <0.94.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{badmatch,[naive_cache_app,{eval,{lists,reverse,[[1,2,3,4,5]]},5000},[],{bad_return_value,undefined},<0.69.0>,[{gen,do_call,4,[{file,"gen.erl"},{line,169}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,202}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,674}]},{shell,exprs,7,[{file,"shell.erl"},{line,687}]},{shell,eval_exprs,7,[{file,"shell.erl"},{line,642}]},{shell,eval_loop,3,[{file,"shell.erl"},{line,627}]}]]},[{error_logger_lager_h,log_event,2,[{file,"src/error_logge..."},...]},...]}}
2017-12-28 12:01:33.773 [error] <0.101.0> CRASH REPORT Process naive_cache_app with 1 neighbours exited with reason: bad return value: undefined in gen_server:handle_common_reply/8 line 730
2017-12-28 12:06:44.204 [error] <0.94.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{badmatch,[naive_cache_app,{eval,{lists,reverse,[[1,2,3]]},5000},[],{bad_return_value,undefined},<0.69.0>,[{gen,do_call,4,[{file,"gen.erl"},{line,169}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,202}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,674}]},{shell,exprs,7,[{file,"shell.erl"},{line,687}]},{shell,eval_exprs,7,[{file,"shell.erl"},{line,642}]},{shell,eval_loop,3,[{file,"shell.erl"},{line,627}]}]]},[{error_logger_lager_h,log_event,2,[{file,"src/error_logger_la..."},...]},...]}}
2017-12-28 12:06:44.207 [error] <0.101.0> CRASH REPORT Process naive_cache_app with 1 neighbours exited with reason: bad return value: undefined in gen_server:handle_common_reply/8 line 730
2017-12-28 12:10:36.309 [error] <0.94.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{badmatch,[naive_cache_app,{eval,{lists,reverse,[[1,2,3]]},5000},[],{bad_return_value,undefined},<0.69.0>,[{gen,do_call,4,[{file,"gen.erl"},{line,169}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,202}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,674}]},{shell,exprs,7,[{file,"shell.erl"},{line,687}]},{shell,eval_exprs,7,[{file,"shell.erl"},{line,642}]},{shell,eval_loop,3,[{file,"shell.erl"},{line,627}]}]]},[{error_logger_lager_h,log_event,2,[{file,"src/error_logger_la..."},...]},...]}}
2017-12-28 12:10:36.313 [error] <0.101.0> CRASH REPORT Process naive_cache_app with 1 neighbours exited with reason: bad return value: undefined in gen_server:handle_common_reply/8 line 730
2017-12-28 12:14:46.573 [error] <0.94.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{badmatch,[naive_cache_app,{eval,{lists,reverse,[[1,2,3]]},5000},[],{bad_return_value,undefined},<0.69.0>,[{gen,do_call,4,[{file,"gen.erl"},{line,169}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,202}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,674}]},{shell,exprs,7,[{file,"shell.erl"},{line,687}]},{shell,eval_exprs,7,[{file,"shell.erl"},{line,642}]},{shell,eval_loop,3,[{file,"shell.erl"},{line,627}]}]]},[{error_logger_lager_h,log_event,2,[{file,"src/error_logger_la..."},...]},...]}}
2017-12-28 12:14:46.578 [error] <0.101.0> CRASH REPORT Process naive_cache_app with 1 neighbours exited with reason: bad return value: undefined in gen_server:handle_common_reply/8 line 730
2017-12-28 12:19:53.518 [error] <0.101.0> CRASH REPORT Process naive_cache_app with 1 neighbours exited with reason: bad return value: ok in gen_server:init_it/6 line 357
2017-12-28 12:20:35.244 [error] <0.101.0> CRASH REPORT Process naive_cache_app with 1 neighbours exited with reason: bad return value: ok in gen_server:init_it/6 line 357
2017-12-28 12:21:35.727 [error] <0.101.0> CRASH REPORT Process naive_cache_app with 1 neighbours exited with reason: bad return value: ok in gen_server:init_it/6 line 357
2017-12-28 12:22:36.645 [error] <0.101.0> CRASH REPORT Process naive_cache_app with 1 neighbours exited with reason: bad return value: ok in gen_server:init_it/6 line 357
2017-12-28 12:26:11.931 [error] <0.94.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{badmatch,[naive_cache_app,{eval,{lists,reverse,[[1,2,3,4]]},5000},[],{bad_return_value,undefined},<0.69.0>,[{gen,do_call,4,[{file,"gen.erl"},{line,169}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,202}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,674}]},{shell,exprs,7,[{file,"shell.erl"},{line,687}]},{shell,eval_exprs,7,[{file,"shell.erl"},{line,642}]},{shell,eval_loop,3,[{file,"shell.erl"},{line,627}]}]]},[{error_logger_lager_h,log_event,2,[{file,"src/error_logger_..."},...]},...]}}
2017-12-28 12:26:11.936 [error] <0.101.0> CRASH REPORT Process naive_cache_app with 1 neighbours exited with reason: bad return value: undefined in gen_server:handle_common_reply/8 line 730
2017-12-28 12:28:00.539 [error] <0.94.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{badmatch,[naive_cache_app,{eval,{lists,reverse,[[1,2,3,4]]},5000},[],{bad_return_value,undefined},<0.69.0>,[{gen,do_call,4,[{file,"gen.erl"},{line,169}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,202}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,674}]},{shell,exprs,7,[{file,"shell.erl"},{line,687}]},{shell,eval_exprs,7,[{file,"shell.erl"},{line,642}]},{shell,eval_loop,3,[{file,"shell.erl"},{line,627}]}]]},[{error_logger_lager_h,log_event,2,[{file,"src/error_logger_..."},...]},...]}}
2017-12-28 12:28:00.542 [error] <0.101.0> CRASH REPORT Process naive_cache_app with 1 neighbours exited with reason: bad return value: undefined in gen_server:handle_common_reply/8 line 730
2017-12-28 12:48:27.771 [error] <0.94.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{badmatch,[a,{execute,{lists,reverse,[[1,2,3,4,5]]},5000,<0.109.0>},[],{bad_return_value,{ok,waiting}},<0.107.0>,[{gen,do_call,4,[{file,"gen.erl"},{line,169}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,202}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,674}]},{shell,exprs,7,[{file,"shell.erl"},{line,687}]},{shell,eval_exprs,7,[{file,"shell.erl"},{line,642}]},{shell,eval_loop,3,[{file,"shell.erl"},{line,627}]}]]},[{error_logger_lager_h,log_event,2,[{file,"src/error_lo..."},...]},...]}}
2017-12-28 12:48:27.773 [error] <0.109.0> CRASH REPORT Process a with 1 neighbours exited with reason: bad return value: {ok,waiting} in gen_server:handle_common_reply/8 line 730
